### ISSUE TITLE
[BUG] Can't create Client with "new" keywork

### ISSUE THREAD

**Issue by pradel** [khaosdoctor/devto-nodejs-sdk#8]
**Describe the bug**

Hey, thanks for this cool lib. I tried to use your client with the README example but using the "new" keyword is creating the following typescript issue:

```
TSError: ⨯ Unable to compile TypeScript:
scripts/syncBlog.ts:3:16 - error TS7009: 'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.

3 const client = new Client('test');
                 ~~~~~~~~~~~~~~~~~~

    at createTSError (/Users/leo/dev/pradel/leopradel.com/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/Users/leo/dev/pradel/leopradel.com/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/Users/leo/dev/pradel/leopradel.com/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/Users/leo/dev/pradel/leopradel.com/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/Users/leo/dev/pradel/leopradel.com/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/leo/dev/pradel/leopradel.com/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
error Command failed with exit code 1.
```

**To Reproduce**

Create a new typescript type and just add the following code snipped:
```
import { Client } from 'devto-nodejs-sdk';

const client = new Client('test');
```

To fix this issue I removed the new keyword

```
import { Client } from 'devto-nodejs-sdk';

const client = Client('test');
```

**Comment by khaosdoctor** [comment]
Hey! Thanks a lot for the bug report, let me fix this ASAP

**Comment by souvikinator** [comment]
Seems like this is still an issue. removing `new` fixed it.
